# Install system library
[tool.cibuildwheel.linux]
# Run multiple commands using an array
before-all = [
  "yum install libhdf5-devel -y",
  "yum install libboost-devel -y",
  "yum install libgsl-devel -y",
]
